networks:
  dev:
    driver: bridge

services:
  db:
    image: postgres:13
    container_name: ${PG_CONTAINER_NAME:-postgres-db}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - dev
    ports:
      - "${PG_PORT_LOCAL}:${PG_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    restart: unless-stopped                      

  backend:
    build: .
    container_name: ${BACKEND_CONTAINER_NAME:-backend}
    depends_on:
      - db
    networks:
      - dev
    environment:
      PG_HOST: db
      PG_PORT: ${PG_PORT}
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATABASE: ${POSTGRES_DB}
      DB_POSTGRE: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PG_PORT}/${POSTGRES_DB}"

    volumes:
      - .:/app
    restart: unless-stopped                       

volumes:
  postgres_data:                                 